In [1]:
import pandas as pd

In [ ]:
# Create a DataFrame
# 1. Using Collection Object
# 2. Loading a file

In [ ]:
#Using Collection Object
#emp (eid,ename,esal)


list1=[
    [1,"shri",900],
    [2,"jeeva",300],
    [3,"vikas",23332]


]
data = pd.DataFrame(list1)
print(data)

   0      1      2
0  1   shri    900
1  2  jeeva    300
2  3  vikas  23332

In [ ]:
# Dataframe contains two types of index
# 1. Row Index
# 2. Column Index

# Index starts from 0

data=pd.DataFrame(list1,columns=["no","name","sal"])
print(data)

   no   name    sal
0   1   shri    900
1   2  jeeva    300
2   3  vikas  23332

In [ ]:
data.info()   # info()---can help us to find the missing values in the dataset and also the data types of the columns in the dataset.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   no      3 non-null      int64
 1   name    3 non-null      object
 2   sal     3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [6]:
import numpy as np
list2=[
    [1,"shri",900],
    [2,"jeeva",np.nan],
    [3,"vikas",23332]
]
data=pd.DataFrame(list2,columns=["no","name","sal"])
print(data)

   no   name      sal
0   1   shri    900.0
1   2  jeeva      NaN
2   3  vikas  23332.0

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   no      3 non-null      int64
 1   name    3 non-null      object
 2   sal     2 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 204.0+ bytes

In [11]:
# Dataframe contains two types of index
# 1. Row Index
# 2. Column Index

# Index starts from 0

#To Load a delimited file
# read_csv()

file1 = pd.read_csv("sample_data/empSpecial.csv")
print(file1)

    eid\tename\tesal
0      1\tPrashant\t
1          2\t\t2000
2    3\tChitra\t2000
3    3\tChitra\t2000
4  4\tUtkarsha\t9878
5      5\tAjit\t9999

In [10]:
file1=pd.read_csv("sample_data/empSpecial.csv",sep='\t')
print(file1)

   eid     ename    esal
0    1  Prashant     NaN
1    2       NaN  2000.0
2    3    Chitra  2000.0
3    3    Chitra  2000.0
4    4  Utkarsha  9878.0
5    5      Ajit  9999.0

In [12]:
# header --- used to specify header in the file (none means no header)
file2 = pd.read_csv("sample_data/employee.csv",header=None)
print(file2)

   0         1     2
0  1  Prashant  1000
1  2      Amar  2000
2  3    Chitra  2000
3  4  Utkarsha  9878
4  5      Ajit  9999

In [13]:
file2= pd.read_csv("sample_data/employee.csv",names=["no","name","id"])
print(file2)

   no      name    id
0   1  Prashant  1000
1   2      Amar  2000
2   3    Chitra  2000
3   4  Utkarsha  9878
4   5      Ajit  9999

In [14]:
file3 = pd.read_csv("sample_data/employeeWithHeaders.csv")
print(file3)

   eid     ename  esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000
3    3    Chitra  2000
4    4  Utkarsha  9878
5    5      Ajit  9999

In [15]:
%%writefile data.csv
1,shriiii,883
2,djd
3,cdn,
3434

pdd = pd.read_csv("data.csv",header=None,on_bad_lines="skip")
print(pdd)

Writing data.csv

In [17]:
#Loading from Github

df = pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")
print(df)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [19]:
df.head() #First 5 entries

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [20]:
df.head(10) #First 10 entries

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

In [21]:
df.tail() #Last 5 records

     sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [22]:
df.tail(10) #Last 10 records

     sepal.length  sepal.width  petal.length  petal.width    variety
140           6.7          3.1           5.6          2.4  Virginica
141           6.9          3.1           5.1          2.3  Virginica
142           5.8          2.7           5.1          1.9  Virginica
143           6.8          3.2           5.9          2.3  Virginica
144           6.7          3.3           5.7          2.5  Virginica
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica