In [1]:
import pandas as pd

In [2]:
op = pd.read_csv("sample_data/employeeWithHeaders.csv")
print(op)

   eid     ename  esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000
3    3    Chitra  2000
4    4  Utkarsha  9878
5    5      Ajit  9999

In [3]:
#if you want columns name
op.columns

Index(['eid', 'ename', 'esal'], dtype='object')

In [4]:
#conversion of pandas into numpy
op.values

array([[1, 'Prashant', 1000],
       [2, 'Amar', 2000],
       [3, 'Chitra', 2000],
       [3, 'Chitra', 2000],
       [4, 'Utkarsha', 9878],
       [5, 'Ajit', 9999]], dtype=object)

In [5]:
#numpy into dataframe
opdata = pd.DataFrame(op)
opdata

   eid     ename  esal
0    1  Prashant  1000
1    2      Amar  2000
2    3    Chitra  2000
3    3    Chitra  2000
4    4  Utkarsha  9878
5    5      Ajit  9999

In [6]:
  #if you want particular columns
opdata['esal']

0    1000
1    2000
2    2000
3    2000
4    9878
5    9999
Name: esal, dtype: int64

In [7]:
#to create the new columns
opdata['yearsal']=0
opdata

   eid     ename  esal  yearsal
0    1  Prashant  1000        0
1    2      Amar  2000        0
2    3    Chitra  2000        0
3    3    Chitra  2000        0
4    4  Utkarsha  9878        0
5    5      Ajit  9999        0

In [8]:
opdata['yearsal']=opdata['esal']*12 #broadcasting
opdata

   eid     ename  esal  yearsal
0    1  Prashant  1000    12000
1    2      Amar  2000    24000
2    3    Chitra  2000    24000
3    3    Chitra  2000    24000
4    4  Utkarsha  9878   118536
5    5      Ajit  9999   119988

In [9]:
#Create a function that can accept salary and return the bonus of the salary
# salary less than or equal to 1500 -----> 10% bonus
# salary between 1501 and 6000 ----------> 5% bonus
# salary between 6001 and 9900 ----------> 2.5% bonus
# salary greater than 9900 --------------> 0 (no bonus)

def bonus(sal):
  if sal <=1500:
    return round(sal * 0.10,3)
  elif sal >=1501 and sal<=6000:
    return round(sal * 0.05,3)
  elif sal>=6001 and sal <=9900:
    return round(sal * 0.025,3)
  elif sal>9900:
    return 0
  else:
    return 0
bonus(9879)

246.975

In [10]:
#Pandas also allows you to broadcast a function logic
#
# Goal : Create a new column named bonussal and calc bonus of each emp
#        based on their salary


# To broadcast a function in Pandas , you can use apply()
opdata['bounsal']=opdata['esal'].apply(bonus)
opdata

   eid     ename  esal  yearsal  bounsal
0    1  Prashant  1000    12000   100.00
1    2      Amar  2000    24000   100.00
2    3    Chitra  2000    24000   100.00
3    3    Chitra  2000    24000   100.00
4    4  Utkarsha  9878   118536   246.95
5    5      Ajit  9999   119988     0.00

In [11]:
#if u want all employee  name in capitall
opdata['ename']=opdata['ename'].apply(str.upper)
opdata

   eid     ename  esal  yearsal  bounsal
0    1  PRASHANT  1000    12000   100.00
1    2      AMAR  2000    24000   100.00
2    3    CHITRA  2000    24000   100.00
3    3    CHITRA  2000    24000   100.00
4    4  UTKARSHA  9878   118536   246.95
5    5      AJIT  9999   119988     0.00

In [13]:
opdata['dept']=pd.Series(["HR","CR","MN","SC","AC","DS"])
opdata

   eid     ename  esal  yearsal  bounsal dept
0    1  PRASHANT  1000    12000   100.00   HR
1    2      AMAR  2000    24000   100.00   CR
2    3    CHITRA  2000    24000   100.00   MN
3    3    CHITRA  2000    24000   100.00   SC
4    4  UTKARSHA  9878   118536   246.95   AC
5    5      AJIT  9999   119988     0.00   DS

In [14]:
# Data traversal --- Accessing data
#
# Accessing data using Index Location -------- iloc
#
# 1. iloc[ rowIndex,colIndex ]
# 2. iloc[ rowRange, colRange ]. ---- series method (startIndex:upperBound)
# 3. iloc[ rowIndexList, colIndexList]


# Access first 3 records

opdata.iloc[ [0,1,2] , [0,1,2,3,4,5] ]

   eid     ename  esal  yearsal  bounsal dept
0    1  PRASHANT  1000    12000    100.0   HR
1    2      AMAR  2000    24000    100.0   CR
2    3    CHITRA  2000    24000    100.0   MN

In [15]:
opdata.iloc[ 0:3 , 0:6 ]

   eid     ename  esal  yearsal  bounsal dept
0    1  PRASHANT  1000    12000    100.0   HR
1    2      AMAR  2000    24000    100.0   CR
2    3    CHITRA  2000    24000    100.0   MN

In [16]:
opdata.iloc[ [0,1,2] , 0:6 ]

   eid     ename  esal  yearsal  bounsal dept
0    1  PRASHANT  1000    12000    100.0   HR
1    2      AMAR  2000    24000    100.0   CR
2    3    CHITRA  2000    24000    100.0   MN

In [17]:
opdata.iloc[ 0,1]

'PRASHANT'

In [18]:
# Goal: Extract those records whose monthly salary is greater than 5000

opdata[ opdata['esal'] > 5000 ]

   eid     ename  esal  yearsal  bounsal dept
4    4  UTKARSHA  9878   118536   246.95   AC
5    5      AJIT  9999   119988     0.00   DS

In [19]:
#Goal: Extract those records who belong to Testing Department

opdata[ opdata['dept'] == "Testing" ]

Empty DataFrame
Columns: [eid, ename, esal, yearsal, bounsal, dept]
Index: []

In [20]:

#Goal: Extract those records who belong to Ops dept and has monthly salary greater than 1500

opdata[ (opdata['dept'] == 'Ops') & (opdata['esal'] > 1500) ]

Empty DataFrame
Columns: [eid, ename, esal, yearsal, bounsal, dept]
Index: []

In [21]:
# Extract the maximum monthly salary

opdata['esal'].max()

9999

In [22]:
# Extract the minimum monthly salary

opdata['esal'].min()

1000

In [23]:
# Extract the average monthly salary

opdata['esal'].mean()

np.float64(4479.5)

In [24]:
# Extract the name of the employee who draws maximum salary

opdata[ opdata['esal'] == opdata['esal'].max() ] ['ename']

5    AJIT
Name: ename, dtype: object

In [25]:
opdata[ opdata['esal'] == opdata['esal'].max() ].iloc[ : ,[1]]

  ename
5  AJIT

In [26]:
opdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   eid      6 non-null      int64
 1   ename    6 non-null      object
 2   esal     6 non-null      int64
 3   yearsal  6 non-null      int64
 4   bounsal  6 non-null      float64
 5   dept     6 non-null      object
dtypes: float64(1), int64(3), object(2)
memory usage: 420.0+ bytes