# DAY 3 : Handling Inappropriate Data  
**Dataset:** datasetExample.csv

In [36]:
# Handling Inappropriate Data
# Usually this step is executed when dealing with EXTERNAL DATASET.
# The secret ingredient to handle Inappropriate data is Having ENOUGH DOMAIN KNOWLEDGE.

In [ ]:
# Guidelines on Handling inappropriate data
# =================================================================================
#
# 1. Identity the type of data for each column (Numerical, categorical, ordinal and purestring)
# 2. Check and remove all Duplicate Records from the dataframe
# 3. Check and remove all Duplicate COlumns from the dataframe
# 4. If your column is Numerical column, perform the following
#
#       - If dealing with Continuous ND, check w.r.t domain whether teh following parameter is valid or not:
#            a. Positive Numbers are allowed or not
#            b. Negative Numbers are allowed or not
#            c. Decimals are allowed or not
#
#           If any of the above is not allowed, DELETE THAT COLUMN ENTRY.
#
#       - If dealing with Discrete ND, check w.r.t domain whether teh following parameter is valid or not:
#            a. Positive Numbers are allowed or not
#            b. Negative Numbers are allowed or not
#            c. Decimals are allowed or not
#            d. Check whether the numbers fall in a specified range as defined by the domain
#
#           If any of the above is not allowed, DELETE THAT COLUMN ENTRY.
#
#
# 5. If the columns are Categorical Columns, perform the following:
#          a. Get the unique values of the column
#          b. Handle the data that has SPELLING ERRORS, CASE ERRORS (Normalization) or any FORMATTING ERRORS. Ensure CASE is UNIFIED
#          c. Check whether the categories/groups found the unique values match the domain spec.
#
#          If any unusual category found, DELETE THAT SPECIFIC RECORD.
#
# 6. If the columns are Ordinal Columns, perform the following:
#          a. Get the unique values of the column
#          b. Handle the data that has SPELLING ERRORS, CASE ERRORS (Normalization) or any FORMATTING ERRORS. Ensure CASE is UNIFIED
#          c. Check whether the categories/groups found the unique values match the domain spec.
#          d. Check the rank of each unique category and ensure it matches teh domain spec.
#
#          If any unusual category/rank found, DELETE THAT SPECIFIC RECORD.
#
# 7. If dealing with date column, convert the datatype of the column into datetime and extract the relevant data from the date column

In [1]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv("sample_data/datasetExample.csv")

In [6]:
data

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary,Age_Group.1
0,1,20-25,4,Ibis,veg,1300,2,40000,20-25
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000,30-35
2,3,25-30,6,RedFox,Veg,1322,2,30000,25-30
3,4,20-25,-1,LemonTree,Veg,1234,2,120000,20-25
4,5,35+,3,Ibis,Vegetarian,989,2,45000,35+
5,6,35+,3,Ibys,Non-Veg,1909,2,122220,35+
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122,35+
7,8,20-25,7,LemonTree,Veg,2999,-10,345673,20-25
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
9,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
10,10,30-35,5,RedFox,non-Veg,-6755,4,87777,30-35

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       11 non-null     int64
 1   Age_Group        11 non-null     object
 2   Rating(1-5)      11 non-null     int64
 3   Hotel            11 non-null     object
 4   FoodPreference   11 non-null     object
 5   Bill             11 non-null     int64
 6   NoOfPax          11 non-null     int64
 7   EstimatedSalary  11 non-null     int64
 8   Age_Group.1      11 non-null     object
dtypes: int64(5), object(4)
memory usage: 924.0+ bytes

In [ ]:
# 1. Identity the type of data for each column (Numerical, categorical, ordinal and purestring)
#   Column           Non-Null Count  Dtype
# ---  ------           --------------  -----
#  0   CustomerID       11 non-null     int64  -------> Numerical (Cont)
#  1   Age_Group        11 non-null     object -------> Categorical
#  2   Rating(1-5)      11 non-null     int64  -------> Numerical (Discrete)
#  3   Hotel            11 non-null     object -------> Categorical (assume)
#  4   FoodPreference   11 non-null     object -------> Categorical
#  5   Bill             11 non-null     int64  -------> Numerical (Cont)
#  6   NoOfPax          11 non-null     int64  -------> Numerical (Cont)
#  7   EstimatedSalary  11 non-null     int64  -------> Numerical (Cont)
#  8   Age_Group.1      11 non-null     object -------> Categorical

In [8]:
#2. Check and remove all Duplicate Records from the dataframe
#
# in Pandas, we can detect and remove duplicate records using drop_duplicates()

# inplace = True ---- committing the operation in the main df
# ignore_index =True ----- resetting the row indexes

data.drop_duplicates(inplace=True, ignore_index=True)
data

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary,Age_Group.1
0,1,20-25,4,Ibis,veg,1300,2,40000,20-25
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000,30-35
2,3,25-30,6,RedFox,Veg,1322,2,30000,25-30
3,4,20-25,-1,LemonTree,Veg,1234,2,120000,20-25
4,5,35+,3,Ibis,Vegetarian,989,2,45000,35+
5,6,35+,3,Ibys,Non-Veg,1909,2,122220,35+
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122,35+
7,8,20-25,7,LemonTree,Veg,2999,-10,345673,20-25
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
9,10,30-35,5,RedFox,non-Veg,-6755,4,87777,30-35

In [9]:
# 3. Check and remove all Duplicate COlumns from the dataframe
#
# In pandas, duplicate column can be identified only if teh dataset has headers and coln name is same
#
# Use column name theory , i.e. check any column with a suffix .(number)
# e.g. AgeGroup.1

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       10 non-null     int64
 1   Age_Group        10 non-null     object
 2   Rating(1-5)      10 non-null     int64
 3   Hotel            10 non-null     object
 4   FoodPreference   10 non-null     object
 5   Bill             10 non-null     int64
 6   NoOfPax          10 non-null     int64
 7   EstimatedSalary  10 non-null     int64
 8   Age_Group.1      10 non-null     object
dtypes: int64(5), object(4)
memory usage: 852.0+ bytes

In [10]:
data[data["Age_Group"]!=data['Age_Group']]

Empty DataFrame
Columns: [CustomerID, Age_Group, Rating(1-5), Hotel, FoodPreference, Bill, NoOfPax, EstimatedSalary, Age_Group.1]
Index: []

In [11]:
#If the above is a null set, it means the given columsn are same. Therefore eliminate one of them
data.drop(columns=['Age_Group.1'],inplace=True)

In [ ]:
# 4. If your column is Numerical column, perform the following
#
#       - If dealing with Continuous ND, check w.r.t domain whether teh following parameter is valid or not:
#            a. Positive Numbers are allowed or not
#            b. Negative Numbers are allowed or not
#            c. Decimals are allowed or not
#
#           If any of the above is not allowed, DELETE THAT COLUMN ENTRY.

#   Column           Non-Null Count  Dtype
# ---  ------           --------------  -----
#  0   CustomerID       11 non-null     int64  -------> Numerical (Cont) | +ve allowed, -ve not allowed, decimal not allowed
#  5   Bill             11 non-null     int64  -------> Numerical (Cont) | +ve allowed, -ve not allowed, decimal allowed
#  6   NoOfPax          11 non-null     int64  -------> Numerical (Cont) | +ve allowed, -ve not allowed, decimal not allowed
#  7   EstimatedSalary  11 non-null     int64  -------> Numerical (Cont) | +ve allowed, -ve not allowed, decimal allowed

In [12]:
data[data["CustomerID"]<0]

Empty DataFrame
Columns: [CustomerID, Age_Group, Rating(1-5), Hotel, FoodPreference, Bill, NoOfPax, EstimatedSalary]
Index: []

In [13]:
data[data["Bill"]<0]

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
9,10,30-35,5,RedFox,non-Veg,-6755,4,87777

In [14]:
data['Bill'].loc[data['Bill']<0]=np.nan
data

C:\Users\shrid\AppData\Local\Temp\ipykernel_46400\101429647.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['Bill'].loc[data['Bill']<0]=np.nan
C:\Users\shrid\AppData\Local\Temp\ipykernel_46400\101429647.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Bill'].loc[data['Bill']<0]=np.nan

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4,Ibis,veg,1300.0,2,40000
1,2,30-35,5,LemonTree,Non-Veg,2000.0,3,59000
2,3,25-30,6,RedFox,Veg,1322.0,2,30000
3,4,20-25,-1,LemonTree,Veg,1234.0,2,120000
4,5,35+,3,Ibis,Vegetarian,989.0,2,45000
5,6,35+,3,Ibys,Non-Veg,1909.0,2,122220
6,7,35+,4,RedFox,Vegetarian,1000.0,-1,21122
7,8,20-25,7,LemonTree,Veg,2999.0,-10,345673
8,9,25-30,2,Ibis,Non-Veg,3456.0,3,-99999
9,10,30-35,5,RedFox,non-Veg,NaN,4,87777

In [15]:
data[data["NoOfPax"]<0]

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
6,7,35+,4,RedFox,Vegetarian,1000.0,-1,21122
7,8,20-25,7,LemonTree,Veg,2999.0,-10,345673

In [16]:
data['NoOfPax'].loc[data['NoOfPax']<0]=np.nan

C:\Users\shrid\AppData\Local\Temp\ipykernel_46400\1882434798.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['NoOfPax'].loc[data['NoOfPax']<0]=np.nan
C:\Users\shrid\AppData\Local\Temp\ipykernel_46400\1882434798.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['NoOfPax'].loc[data['NoOfPax']<0]=np.nan

In [17]:
data

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4,Ibis,veg,1300.0,2.0,40000
1,2,30-35,5,LemonTree,Non-Veg,2000.0,3.0,59000
2,3,25-30,6,RedFox,Veg,1322.0,2.0,30000
3,4,20-25,-1,LemonTree,Veg,1234.0,2.0,120000
4,5,35+,3,Ibis,Vegetarian,989.0,2.0,45000
5,6,35+,3,Ibys,Non-Veg,1909.0,2.0,122220
6,7,35+,4,RedFox,Vegetarian,1000.0,NaN,21122
7,8,20-25,7,LemonTree,Veg,2999.0,NaN,345673
8,9,25-30,2,Ibis,Non-Veg,3456.0,3.0,-99999
9,10,30-35,5,RedFox,non-Veg,NaN,4.0,87777

In [18]:
data[data['EstimatedSalary']<0]

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
8,9,25-30,2,Ibis,Non-Veg,3456.0,3.0,-99999

In [19]:
data['EstimatedSalary'].loc[data['EstimatedSalary']<0]=np.nan

C:\Users\shrid\AppData\Local\Temp\ipykernel_46400\1458577211.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['EstimatedSalary'].loc[data['EstimatedSalary']<0]=np.nan
C:\Users\shrid\AppData\Local\Temp\ipykernel_46400\1458577211.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['EstimatedSalary'].loc[data['EstimatedSalary']<0]=np.nan

In [20]:
data

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4,Ibis,veg,1300.0,2.0,40000.0
1,2,30-35,5,LemonTree,Non-Veg,2000.0,3.0,59000.0
2,3,25-30,6,RedFox,Veg,1322.0,2.0,30000.0
3,4,20-25,-1,LemonTree,Veg,1234.0,2.0,120000.0
4,5,35+,3,Ibis,Vegetarian,989.0,2.0,45000.0
5,6,35+,3,Ibys,Non-Veg,1909.0,2.0,122220.0
6,7,35+,4,RedFox,Vegetarian,1000.0,NaN,21122.0
7,8,20-25,7,LemonTree,Veg,2999.0,NaN,345673.0
8,9,25-30,2,Ibis,Non-Veg,3456.0,3.0,NaN
9,10,30-35,5,RedFox,non-Veg,NaN,4.0,87777.0

In [ ]:
#       - If dealing with Discrete ND, check w.r.t domain whether teh following parameter is valid or not:
#            a. Positive Numbers are allowed or not
#            b. Negative Numbers are allowed or not
#            c. Decimals are allowed or not
#            d. Check whether the numbers fall in a specified range as defined by the domain
#
#           If any of the above is not allowed, DELETE THAT COLUMN ENTRY.
#

#   Column           Non-Null Count  Dtype
# ---  ------           --------------  -----

#  2   Rating(1-5)      11 non-null     int64  -------> Numerical (Discrete) | +ve allowed, -ve not allowed, decimals not allowed, range is 1,2,3,4,5

In [22]:
data[(data['Rating(1-5)']<0) | (data["Rating(1-5)"]>5)]

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
2,3,25-30,6,RedFox,Veg,1322.0,2.0,30000.0
3,4,20-25,-1,LemonTree,Veg,1234.0,2.0,120000.0
7,8,20-25,7,LemonTree,Veg,2999.0,NaN,345673.0

In [23]:
data["Rating(1-5)"].loc[(data['Rating(1-5)']<0) | (data["Rating(1-5)"]>5)]=np.nan

C:\Users\shrid\AppData\Local\Temp\ipykernel_46400\1702896085.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data["Rating(1-5)"].loc[(data['Rating(1-5)']<0) | (data["Rating(1-5)"]>5)]=np.nan
C:\Users\shrid\AppData\Local\Temp\ipykernel_46400\1702896085.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Rating(1-5)"].loc[(data['Rating(1-5)']<0) | (data["Rating(1-5)"]>5)]=np.nan

In [24]:
data

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4.0,Ibis,veg,1300.0,2.0,40000.0
1,2,30-35,5.0,LemonTree,Non-Veg,2000.0,3.0,59000.0
2,3,25-30,NaN,RedFox,Veg,1322.0,2.0,30000.0
3,4,20-25,NaN,LemonTree,Veg,1234.0,2.0,120000.0
4,5,35+,3.0,Ibis,Vegetarian,989.0,2.0,45000.0
5,6,35+,3.0,Ibys,Non-Veg,1909.0,2.0,122220.0
6,7,35+,4.0,RedFox,Vegetarian,1000.0,NaN,21122.0
7,8,20-25,NaN,LemonTree,Veg,2999.0,NaN,345673.0
8,9,25-30,2.0,Ibis,Non-Veg,3456.0,3.0,NaN
9,10,30-35,5.0,RedFox,non-Veg,NaN,4.0,87777.0

In [ ]:
# 5. If the columns are Categorical Columns, perform the following:
#          a. Get the unique values of the column
#          b. Handle the data that has SPELLING ERRORS, CASE ERRORS (Normalization) or any FORMATTING ERRORS. Ensure CASE is UNIFIED
#          c. Check whether the categories/groups found the unique values match the domain spec.
#
#          If any unusual category found, DELETE THAT SPECIFIC RECORD.

#   Column           Non-Null Count  Dtype
# ---  ------           --------------  -----

#  1   Age_Group        11 non-null     object -------> Categorical
#  3   Hotel            11 non-null     object -------> Categorical (assume)
#  4   FoodPreference   11 non-null     object -------> Categorical

#

In [25]:
data["Age_Group"].unique()

array(['20-25', '30-35', '25-30', '35+'], dtype=object)

In [ ]:
##Hotel

#          a. Get the unique values of the column
#In pandas --------- unique()

data["Hotel"]=data["Hotel"].apply(str.lower)

In [28]:
data['Hotel'].unique()

array(['ibis', 'lemontree', 'redfox', 'ibys'], dtype=object)

In [ ]:
# In Pandas, we can use replace function
#
# pd.replace( source, destination )
data["Hotel"].replace(['ibys'], ['ibis'], inplace=True)

In [30]:
data

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4.0,ibis,veg,1300.0,2.0,40000.0
1,2,30-35,5.0,lemontree,Non-Veg,2000.0,3.0,59000.0
2,3,25-30,NaN,redfox,Veg,1322.0,2.0,30000.0
3,4,20-25,NaN,lemontree,Veg,1234.0,2.0,120000.0
4,5,35+,3.0,ibis,Vegetarian,989.0,2.0,45000.0
5,6,35+,3.0,ibis,Non-Veg,1909.0,2.0,122220.0
6,7,35+,4.0,redfox,Vegetarian,1000.0,NaN,21122.0
7,8,20-25,NaN,lemontree,Veg,2999.0,NaN,345673.0
8,9,25-30,2.0,ibis,Non-Veg,3456.0,3.0,NaN
9,10,30-35,5.0,redfox,non-Veg,NaN,4.0,87777.0

In [32]:
data['FoodPreference']=data["FoodPreference"].apply(str.lower)
data['FoodPreference'].unique()

array(['veg', 'non-veg', 'vegetarian'], dtype=object)

In [34]:
data['FoodPreference'].replace(['vegitarian'], 'veg', inplace=True)

In [35]:
data

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4.0,ibis,veg,1300.0,2.0,40000.0
1,2,30-35,5.0,lemontree,non-veg,2000.0,3.0,59000.0
2,3,25-30,NaN,redfox,veg,1322.0,2.0,30000.0
3,4,20-25,NaN,lemontree,veg,1234.0,2.0,120000.0
4,5,35+,3.0,ibis,vegetarian,989.0,2.0,45000.0
5,6,35+,3.0,ibis,non-veg,1909.0,2.0,122220.0
6,7,35+,4.0,redfox,vegetarian,1000.0,NaN,21122.0
7,8,20-25,NaN,lemontree,veg,2999.0,NaN,345673.0
8,9,25-30,2.0,ibis,non-veg,3456.0,3.0,NaN
9,10,30-35,5.0,redfox,non-veg,NaN,4.0,87777.0